#!/bin/sh

prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
version=0.2.8

if test $# -eq 0; then
   echo "Usage: rote-config [--cflags] [--libs]"
   echo "       rote-config --version"
   echo
fi

while test $# -gt 0; do
   case $1 in
      --cflags)
         echo "-I$includedir"
         ;;
      --libs)
         echo "-L$libdir -lrote"
         ;;
      --version)
         echo "ROTE version $version"
         echo "Our Own Terminal Emulation Library"
         echo
         echo "Copyright (c) 2004 Bruno T. C. de Oliveira"
         echo "All rights reserved"
         ;;
   esac
   shift
done

